name: CI

on:
  push:
    branches: 
      - dev

jobs:

  test:
    name: database health check

    runs-on: ubuntu-latest
    container: node:14.17.1

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: scheduling
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          node --version
          npm --version
      - name: install
        run: |
          cd app
          npm install
      - name: run
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: scheduling
          PGUSER: dev
          PGPASSWORD: dev
          DATABASE_URL: postgres://dev:dev@localhost:5432/scheduling
        run: |
          cd app
          npm run ping:database

  
