name: CI

on:
  push:
    branches: 
      - dev

jobs:

  test:
    name: database health check

    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: scheduling
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
      - name: install
        run: |
          cd app
          npm install
      - name: run
        env:
          PGHOST: localhost
          PGDATABASE: scheduling
          PGUSER: dev
          PGPASSWORD: dev
        run: |
          cd app
          npm run ping:database
          npm test

  
