name: tests

on:
  push:
    branches: 
      - dev

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
      - name: setup firefox
        uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      - run: npm install
      - run: MOZ_HEADLESS=1 npm test
