name: yop-resto

on:
  push:
    branches:
      - heroku

jobs:

  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "yop-resto"
        heroku_email: "eric.mignot+scheduling@gmail.com"
        usedocker: true
        appdir: app
        docker_heroku_process_type: web
        stack: container
        healthcheck: "https://yop-resto.herokuapp.com/ping"
        delay: 33